spring:
  application:
    name: heathCare
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: raissamich12@gmail.com
    url: jdbc:postgresql://localhost:5432/Healthcare
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8089